theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
tab = " "
newline = ""

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
C-s = ":w"
C-q = ":q"
W = ":bc"
J = ":bp"
K = ":bn"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
space = { i = ":cd %:p:h" }
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
"C-s" = ["normal_mode", ":w", "insert_mode"]
"C-o" = ["open_below"]
