env:
  TERM: xterm-256color
import:
  - ./catppuccin-mocha.yml
font:
  size: 9.0
  normal:
    family: FiraCode Nerd Font
    style: Retina
  bold:
    family: FiraCode Nerd Font
    style: Bold
  italic:
    family: FiraCode Nerd Font
    style: Italic
  bold_italic:
    family: FiraCode Nerd Font
    style: Bold Italic
cursor:
  style:
    blinking: Always
    blink_interval: 500
window:
  padding:
    x: 5
    y: 3
  dynamic_title: true
shell:
  program: /usr/sbin/fish
  args:
   - -l
   - -c
   - "tmux attach || tmux"
