import:
  - ~/.config/alacritty/catppuccin-mocha.yml
  - ~/.config/alacritty/keys.yml
env:
  TERM: xterm-256color
font:
  size: 8.0
  normal:
    family: FiraCode Nerd Font
    style: Retina
  bold:
    family: FiraCode Nerd Font
    style: Bold
  italic:
    family: FiraCode Nerd Font
    style: Italic
  bold_italic:
    family: FiraCode Nerd Font
    style: Bold Italic
cursor:
  style:
    blinking: Always
    blink_interval: 500
window:
  padding:
    x: 1
    y: 1
  dynamic_title: true
shell:
  program: /usr/bin/fish
  args:
   - -l
   - -c
   - "tmux new -A -s terminal"
