#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5


MIME=$(file --mime-type -b "$file")

case "$MIME" in
		*image/*)
				kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file"
				exit 1
				;;
    # .pdf
    *application/pdf*)
        pdftotext "$file" -
        ;;
    # .7z
    *application/x-7z-compressed*)
        7z l "$file"
        ;;
    # .tar .tar.Z
    *application/x-tar*)
        tar -tvf "$file"
        ;;
    # .tar.*
    *application/x-compressed-tar*|*application/x-*-compressed-tar*)
        tar -tvf "$file"
        ;;
    # .rar
    *application/vnd.rar*)
        unrar l "$file"
        ;;
    # .zip
    *application/zip*)
        unzip -l "$file"
        ;;
    # any plain text file that doesn't have a specific handler
    *text/*)
        # return false to always repaint, in case terminal size changes
        bat --force-colorization --paging=never --style=changes,numbers \
            --terminal-width $(($2 - 3)) "$file" && false
        ;;
    *)
        echo "unknown format"
        ;;
esac
