# ██╗  ██╗███████╗██╗     ██╗██╗  ██╗
# ██║  ██║██╔════╝██║     ██║╚██╗██╔╝
# ███████║█████╗  ██║     ██║ ╚███╔╝ 
# ██╔══██║██╔══╝  ██║     ██║ ██╔██╗ 
# ██║  ██║███████╗███████╗██║██╔╝ ██╗
# ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝╚═╝  ╚═╝
# github.com/GazDuckington

theme = "catppuccin_mocha"

[editor]
auto-save = true
cursorline = true
color-modes = true
bufferline = "multiple"
line-number = "relative"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
tab = "|"
newline = ""

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
C-s = ":w"
C-q = ":q"
W = ":bc"
H = ":bp"
L = ":bn"
K = "hover"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-p = "command_palette"
esc = ["collapse_selection", "keep_primary_selection"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]

[keys.select]
C-s = ["normal_mode", ":w"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]

[keys.normal.space]
i = ":cd %:p:h"
"." = ":config-open"
">" = ":config-reload"

[keys.insert]
C-e = "completion"
C-c = "toggle_comments"
C-s = ["normal_mode", ":w"]
C-o = "open_below"
A-k = ["normal_mode", "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-j = ["normal_mode", "extend_to_line_bounds", "delete_selection", "paste_after"]
