"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 5000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$golang\
$lua\
$python\
$package\
$cmd_duration\
$line_break\
$jobs$character"""

[fill]
symbol = " "

[line_break]
disabled = false

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vimcmd_symbol = "[](bold green)"
vimcmd_visual_symbol = "[](bold purple)"
vimcmd_replace_one_symbol = "[](bold yellow)"
vimcmd_replace_symbol = "[](bold yellow)"

[username]
disabled = true
show_always = true
style_user = "bold blue"
style_root = "bold red"
format = "[$user]($style)"

[hostname]
disabled = true
ssh_only = false
format = "@[$hostname](bold purple)"

[shell]
disabled = false

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 3
read_only = "⍉"
format = "[$path](cyan) "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"

[time]
disabled = false
style = "bright-black"
format = "[$time]($style) "
time_format = ' %H:%M'

[aws]
symbol = "  "

[conda]
format = '[$symbol($version )]($style)'
symbol = " "

[dart]
format = '[$symbol($version )]($style)'
symbol = " "

[docker_context]
symbol = " "

[elixir]
format = '[$symbol$context]($style)'
symbol = " "

[elm]
format = '[$symbol$context]($style)'
symbol = " "

[hg_branch]
symbol = " "

[golang]
format = '[$symbol($version )]($style)'
symbol = " "

[java]
format = '[$symbol($version )]($style)'
symbol = " "

[julia]
format = '[$symbol($version )]($style)'
symbol = " "

[memory_usage]
symbol = " "

[nim]
format = '[$symbol($version )]($style)'
symbol = " "

[nix_shell]
symbol = " "

[package]
format = '[$symbol($version )]($style)'
symbol = " "

[perl]
format = '[$symbol($version )]($style)'
symbol = " "

[php]
format = '[$symbol($version )]($style)'
symbol = " "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[ruby]
format = '[$symbol($version )]($style)'
symbol = " "

[rust]
format = '[$symbol($version )]($style)'
symbol = " "

[scala]
format = '[$symbol($version )]($style)'
symbol = " "

[shlvl]
format = '[$symbol$shlvl]($style)'
symbol = " "

[swift]
format = '[$symbol($version )]($style)'
symbol = "ﯣ "

[lua]
format = '[$symbol($version )]($style)'
symbol = " "

[nodejs]
format = '[$symbol($version )]($style)'
symbol = " "
