#!/usr/bin/env bash

declare -A menu=(
    ["Shutdown"]="i3exit shutdown"
    ["Restart"]="i3exit reboot"
    ["Lock"]="i3exit lock"
    ["Sleep"]="i3exit suspend"
    ["Logout"]="i3exit logout"
    )


function main() {
  local -r IFS=$'\n'
  [[ $# -ne 0 ]] && eval "${menu[$1]}" || echo "${!menu[*]}"
}

main $@
