#!/usr/bin/env bash

declare -A opt=(
    ["screen"]="sleep 1;\
        scrot 'Screenshot_%Y-%m-%d-%S_$wx$h.png' -e\
        'mv $f $$(xdg-user-dir PICTURES) ;\
        viewnior $$(xdg-user-dir PICTURES)/$f'"
    ["area"]="scrot -s 'Screenshot_%Y-%m-%d-%S_$wx$h.png' -e 'mv $f $$(xdg-user-dir PICTURES) ; viewnior $$(xdg-user-dir PICTURES)/$f'"
    ["window"]="sleep 1; scrot -u 'Screenshot_%Y-%m-%d-%S_$wx$h.png' -e 'mv $f $$(xdg-user-dir PICTURES) ; viewnior $$(xdg-user-dir PICTURES)/$f'"
)

function main() {
  local -r IFS=$'\n'
  [[ $# -ne 0 ]] && eval "${opt[$1]}" || echo "${!opt[*]}"
}

main $@
