#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 

# bsp-layout
bsp-layout set tall -- --master-size 0.55 &

# bspc config automatic_scheme longest_side
#bspc config initial_polarity second_child
#bspc config removal_adjustment false

bspc config border_width         1
bspc config window_gap           5
bspc config border_radius        10
# bspc config split_ratio          0.55
bspc config top_padding          20
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#4796d9
bspc config normal_border_color \#202020

bspc rule -a dropdown state=floating follow=on
bspc rule -a kitty desktop='1' state=tiled
bspc rule -a VSCodium desktop='2'
bspc rule -a DesktopEditors desktop='2'
bspc rule -a Nemo desktop='3'
bspc rule -a Motrix desktop='3'
bspc rule -a Stremio desktop='4'
bspc rule -a Lxappearance desktop='5' state=floating
bspc rule -a Kvantum\ Manager desktop='5' state=floating
bspc rule -a Firewall-config desktop='6'
bspc rule -a musikcube desktop='6' state=pseudo_tiled
bspc rule -a termusic desktop='6' state=pseudo_tiled
bspc rule -a UpdateInTerminal desktop='6' state=pseudo_tiled follow=on
bspc rule -a btop desktop='6' state=pseudo_tiled follow=on

bspc rule -a Arandr state=floating
bspc rule -a pulsemixer state=floating rectangle=600x300+500+25
bspc rule -a nmtui state=floating rectangle=600x600+500+25

# polybar
~/.config/bspwm/polybar

# picom
picom -b &

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
/usr/lib/polkit-kde-authentication-agent-1 &
xsetroot -cursor_name left_ptr &
~/bin/autostart
~/bin/disableETPS 0 &
nitrogen --restore &
parcellite &

