#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width	1
bspc config window_gap		2
bspc config split_ratio		0.52
bspc config top_padding     15

# colors
bspc config focused_border_color "#45A9F9"
bspc config normal_border_color  "#969696"
bspc config active_border_color  "#0FBDBD"

# rules
bspc rule -a kitty desktop=1 follow=off
bspc rule -a VSCodium desktop=2 follow=off
bspc rule -a musikcube desktop=3 follow=off
bspc rule -a Quodlibet desktop=3 follow=off
bspc rule -a Stremio desktop=4 follow=off
bspc rule -a Lxappearance desktop=5 follow=off
bspc rule -a "Kvantum Manager" desktop=5 follow=off
bspc rule -a pulsemixer state=floating rectangle=600x300+500+50
bspc rule -a nmtui state=floating rectangle=600x500+500+50
bspc rule -a hint state=floating rectangle=800x800+500+50
bspc rule -a btop state=floating rectangle=700x700+500+50
bspc rule -a "Android Emulator*" state=floating rectangle=800x800+400+50
bspc rule -a "RAIL*" desktop=3
bspc rule -a "Microsoft Windows" desktop=3

# autostart
~/scripts/launch-polybar.sh &
xsetroot -cursor_name left_ptr &
pkill xidlehook &
~/scripts/idle.sh -s &
~/scripts/hsetrand.sh &
xinput set-prop "ETPS/2 Elantech TrackPoint" "Device Enabled" 0 &
xinput set-prop "ETPS/2 Elantech Touchpad" "Device Enabled" 0 &
xinput set-prop "AT Translated Set 2 keyboard" "Device Enabled" 0 &
dunst &
picom -b &
lxpolkit &
setterm -powersave off -blank 0 &
watch -n 30 ~/scripts/battery-check.sh &
