#! /bin/sh
bspc monitor -d 1 2 3 4 5 6

bspc config automatic_scheme=longest_side

bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.55
bspc config top_padding 20
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focused_border_color \#4796d9
bspc config normal_border_color \#636c7e

bspc config external_rules_command $HOME/.config/bspwm/external_rules

# bsp-layout
bsp-layout set tall -- --master-size 0.6 --desktop 1,3,4,5,6 &

# polybar
~/.config/polybar/scripts/launch-polybar.sh bspbar &

# picom
picom --experimental-backends -b & 

# dropdown terminal
# kitty --class dropdown &

# autostart
pgrep -x sxhkd >/dev/null || sxhkd &
/usr/lib/polkit-kde-authentication-agent-1 &
xsetroot -cursor_name left_ptr &
~/bin/autostart &
~/bin/disableETPS 0 &
nitrogen --restore &
pgrep -x nm-applet >/dev/null || nm-applet &
pgrep -x copyq >/dev/null || copyq &
pgrep -x udiskie >/dev/null || udiskie -t &
