#!/usr/bin/env bash
wid=$1
class=$2
instance=$3
consequences=$4
title=$(xdotool getwindowname $wid)

case "$class" in
	nmtui|pulsemixer|[Nn]m-connection-editor)
		echo "state=floating"
                echo "layer=above"
		echo "rectangle=600x500+500+50"
		;;
	qView|UpdateInTerminal|Arandr|Nitrogen|copyq)
		echo "state=floating"
                echo "layer=above"
                ;;
       	dropdown|musikcube)
		echo "state=floating"
		echo "layer=above"
		echo "sticky=on"
                echo "hidden=on"
		;;
	firefox*|kitty|Zathura)
		echo "desktop=^1"
		echo "follow=on"
		;;
	VSCodium|DesktopEditors)
		echo "desktop=^2"
		echo "follow=on"
		;;
	Nemo|Motrix|qBittorrent)
		echo "desktop=^3"
		echo "follow=on"
		;;
	ru-turikhay-tlauncher-bootstrap-Bootstrap|ATLauncher)
		echo "desktop=^4" 
		echo "state=pseudo_tiled"
                echo "follow=on"
		;;
        Minecraft*)
                echo "desktop=^4"
                echo "follow=on"
                ;;
	Com.github.tchx84.Flatseal|Lxappearance|Kvantum\ Manager|Firewall-config)
		echo "desktop=^5"
		echo "state=pseudo_tiled"
		echo "follow=on"
		;;
	btop|Stremio)
		echo "desktop=^6"
		# echo "state=pseudo_tiled"
		echo "follow=on"
		;;
esac

case "$title" in
	^Library$|^Pick&)
		echo "state=floating"
                echo "layer=above"
	;;
esac
