[theme]
name = "native"
[icons]
name = "material-nf"

# [[block]]
# block = "music"
# buttons = ["prev", "play", "next"]
# [block.theme_overrides]
# info_fg = "#16a085"
[[block]]
block = "focused_window"
max_width = 30
show_marks = "all"
format = "{combo}"

[[block]]
block = "pacman"
interval = 600
format = "PAC:{pacman} AUR:{aur}"
format_singular = "{both}"
format_up_to_date = "0"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "yay -Qua"
on_click = "~/scripts/kitty-launch.sh yay -Qu"
[block.theme_overrides]
info_fg = "#45A9F9"
good_fg = "#45A9F9"
warning_fg = "#FFB86C"
critical_fg = "#FF2C6D"

[[block]]
block = "temperature"
format = "{average}"
interval = 10
chip = "*-isa-*"
collapsed = false
[block.theme_overrides]
good_fg = "#19f9d8"
warning_fg = "#FFB86C"
critical_fg = "#FF2C6D"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95
on_click = "~/scripts/kitty-launch.sh btop"
[block.theme_overrides]
idle_fg = "#19f9d8"
good_fg = "#19f9d8"
warning_fg = "#FFB86C"
critical_fg = "#FF2C6D"

[[block]]
block = "cpu"
interval = 1
on_click = "~/scripts/kitty-launch.sh btop"
[block.theme_overrides]
idle_fg = "#19f9d8"
good_fg = "#19f9d8"
warning_fg = "#FFB86C"
critical_fg = "#FF2C6D"

# [[block]]
# block = "backlight"
# device = "intel_backlight"

[[block]]
block = "sound"
driver = "pulseaudio"
headphones_indicator = true
on_click = "~/scripts/kitty-launch.sh pulsemixer"

[[block]]
block = "time"
interval = 5
format = "%a %d/%b %R"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
[block.theme_overrides]
good_fg = "#19f9d8"
warning_fg = "#FFB86C"
critical_fg = "#FF2C6D"

[[block]]
block = "net"
device = "wlp6s0"
format = "{signal_strength}{speed_down;K*b}{speed_up;K*b}"
on_click = "~/scripts/kitty-launch.sh nmtui"
interval = 5

[[block]]
block = "custom"
interval = 0.5
command = "~/scripts/idle.sh -c"
on_click = "~/scripts/idle.sh -t"

[[block]]
block = "custom"
interval = 0.5
command = "~/scripts/cns.sh -c"

[[block]]
block = "custom"
command = "echo ⏼"
on_click = "~/scripts/powermenu.sh"
