#!/usr/bin/sh
# flutter-dev
export JAVA_HOME="/usr/lib/jvm/default"
export PATH="$JAVA_HOME/bin:$PATH"
export ANDROID="$HOME/Android"
export ANDROID_HOME="$HOME/Android"
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export PATH="$ANDROID/cmdline-tools/tools:$PATH"
export PATH="$ANDROID/cmdline-tools/tools/bin:$PATH"
export PATH="$ANDROID/platform-tools:$PATH"
export PATH="$ANDROID:$PATH"
export PATH="$ANDROID_HOME:$PATH"
export PATH="$ANDROID_SDK_ROOT:$PATH"
export FLUTTER="$ANDROID/flutter"
export PATH="$FLUTTER/bin:$PATH"
export CHROME_EXECUTABLE="/var/lib/flatpak/exports/bin/com.brave.Browser"
# flutter-dev end

# fly.io
export FLYCTL_INSTALL="/home/gaz/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"
# end of fly.io

export XDG_DESKTOP_DIR="$HOME"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_MUSIC_DIR="$HOME/Music"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_SCREENSHOTS_DIR="$XDG_PICTURES_DIR/Screenshots/"
export XDG_VIDEOS_DIR="$HOME/Videos"
export XDG_DOCUMENTS_DIR="$HOME/Documents"

export HISTFILE="$XDG_STATE_HOME"/bash/history
export CARGO_HOME="$HOME"/cargo
export GNUPGHOME="$HOME"/gnupg
export GOPATH="$HOME"/.go
export GOBIN=$(go env GOPATH)/bin
export XCURSOR_PATH=/usr/share/icons:"$XDG_DATA_HOME"/icons
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc 

export GO111MODULE=on
export XCURSOR_PATH="$XCURSOR_PATH":~/.local/share/icons
export FZF_DEFAULT_OPTS='--bind=alt-k:up,alt-j:down'

# path
export PATH="$GOPATH/bin:$PATH"
export PATH="$HOME/cargo/bin:$PATH"
export PATH="$HOME/.local/share/cargo/bin:$PATH"
export PATH="$HOME/.local/share/pyenv/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.surrealdb:$PATH"
export PATH="$HOME/.nix-profile/bin:$PATH"
export PATH="$HOME/.deno/bin:$PATH"
export PATH="$HOME/.local/share/nvim/mason/bin:$PATH"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

export PNPM_HOME="/home/gaz/.local/share/pnpm/"
export PATH="$PNPM_HOME:$PATH"

export DENO_HOME="/home/gaz/.deno/bin"
export PATH="$DENO_HOME:$PATH"

export NPM_CONFIG_PREFIX=~/.npm-global
export PATH="$NPM_CONFIG_PREFIX/.npm-global/bin:$PATH"

export PATH="$HOME/.local/pipx/venvs/:$PATH"
export PATH="$HOME/.spicetify:$PATH"
# export QUARTO_HOME="$HOME/opt/quarto-1.2.335/"
# export PATH="$QUARTO_HOME/bin"

# export DOCKER_HOST=unix:///run/user/1000/docker.sock

export NVIM_SESSION="$HOME/.local/share/nvim/sessions/"

export MODULAR_HOME="$HOME/.modular"
export PATH="$MODULAR_HOME/pkg/packages.modular.com_mojo/bin:$PATH"
