#!/usr/bin/sh
# flutter-dev
## java
export JAVA_HOME='/usr/lib/jvm/java-8-openjdk'
export PATH="$JAVA_HOME/bin:$PATH"
## android
export ANDROID="$HOME/Android"
export PATH="$ANDROID/cmdline-tools/latest:$PATH"
export PATH="$ANDROID/cmdline-tools/latest/bin:$PATH"
export PATH="$ANDROID/platform-tools:$PATH"
## android SDK
export ANDROID_SDK="$HOME/ANDROID"
export PATH="$ANDROID_SDK:$PATH"
## flutter
export FLUTTER="$ANDROID/flutter"
export PATH="$FLUTTER/bin:$PATH"
export CHROME_EXECUTABLE="/var/lib/flatpak/exports/bin/com.brave.Browser"
# flutter-dev end

# fly.io
export FLYCTL_INSTALL="/home/gaz/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"
# end of fly.io

export XDG_DESKTOP_DIR="$HOME/"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DOWNLOAD_DIR="$HOME/Downloads/"
export XDG_MUSIC_DIR="$HOME/Music/"
export XDG_PICTURES_DIR="$HOME/Pictures/"
export XDG_VIDEOS_DIR="$HOME/Videos/"
export XDG_DOCUMENTS_DIR="$HOME/Documents/"

export HISTFILE="$XDG_STATE_HOME"/bash/history
export CARGO_HOME="$HOME"/cargo
export GNUPGHOME="$HOME"/gnupg
export GOPATH="$HOME"/.go
export XCURSOR_PATH=/usr/share/icons:"$XDG_DATA_HOME"/icons
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc 

export GO111MODULE=on
export XCURSOR_PATH="$XCURSOR_PATH":~/.local/share/icons
export FZF_DEFAULT_OPTS='--bind=alt-k:up,alt-j:down'

# path
export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="$HOME/cargo/bin:$PATH"
export PATH="$HOME/.local/share/cargo/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
export PATH="$HOME/.pyenv/bin:$PATH"
export PATH="$HOME/.local/share/pyenv/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.surrealdb:$PATH"
export PATH="$HOME/.nix-profile/bin:$PATH"
export PATH="$HOME/.deno/bin:$PATH"
export PATH="$HOME/.local/share/nvim/mason/bin:$PATH"

export PNPM_HOME="/home/gaz/.local/share/pnpm/"
export PATH="$PNPM_HOME:$PATH"

export DENO_HOME="/home/gaz/.deno/bin"
export PATH="$DENO_HOME:$PATH"

export QUARTO_HOME="$HOME/opt/quarto-1.2.335/"
export PATH="$QUARTO_HOME/bin"
