#!/usr/bin/sh

if [ "$TERM" = "linux" ]; then
	printf %b '\e]P01E1E2E' # set background color to "Base"
	printf %b '\e]P8585B70' # set bright black to "Surface2"

	printf %b '\e]P7BAC2DE' # set text color to "Text"
	printf %b '\e]PFA6ADC8' # set bright white to "Subtext0"

	printf %b '\e]P1F38BA8' # set red to "Red"
	printf %b '\e]P9F38BA8' # set bright red to "Red"

	printf %b '\e]P2A6E3A1' # set green to "Green"
	printf %b '\e]PAA6E3A1' # set bright green to "Green"

	printf %b '\e]P3F9E2AF' # set yellow to "Yellow"
	printf %b '\e]PBF9E2AF' # set bright yellow to "Yellow"

	printf %b '\e]P489B4FA' # set blue to "Blue"
	printf %b '\e]PC89B4FA' # set bright blue to "Blue"

	printf %b '\e]P5F5C2E7' # set magenta to "Pink"
	printf %b '\e]PDF5C2E7' # set bright magenta to "Pink"

	printf %b '\e]P694E2D5' # set cyan to "Teal"
	printf %b '\e]PE94E2D5' # set bright cyan to "Teal"

	clear
fi

# flutter-dev
## java
export JAVA_HOME='/usr/lib/jvm/java-8-openjdk'
export PATH="$JAVA_HOME/bin:$PATH"
## android
export ANDROID="$HOME/Android"
export PATH="$ANDROID/cmdline-tools/latest:$PATH"
export PATH="$ANDROID/cmdline-tools/latest/bin:$PATH"
export PATH="$ANDROID/platform-tools:$PATH"
## android SDK
export ANDROID_SDK="$HOME/ANDROID"
export PATH="$ANDROID_SDK:$PATH"
## flutter
export FLUTTER="$ANDROID/flutter"
export PATH="$FLUTTER/bin:$PATH"
export CHROME_EXECUTABLE="/var/lib/flatpak/exports/bin/com.brave.Browser"
# flutter-dev end

# fly.io
export FLYCTL_INSTALL="/home/gaz/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"
# end of fly.io

export XDG_DESKTOP_DIR="$HOME/"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DOWNLOAD_DIR="$HOME/Downloads/"
export XDG_MUSIC_DIR="$HOME/Music/"
export XDG_PICTURES_DIR="$HOME/Pictures/"
export XDG_VIDEOS_DIR="$HOME/Videos/"
export XDG_DOCUMENTS_DIR="$HOME/Documents/"

export HISTFILE="${XDG_STATE_HOME}"/bash/history
export CARGO_HOME="$HOME"/cargo
export GNUPGHOME="$HOME"/gnupg
export GOPATH="$HOME"/.go
export XCURSOR_PATH=/usr/share/icons:"${XDG_DATA_HOME}"/icons
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc 

export GO111MODULE=on
export XCURSOR_PATH="${XCURSOR_PATH}":~/.local/share/icons
export FZF_DEFAULT_OPTS='--bind=alt-k:up,alt-j:down'

# path
export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="$HOME/cargo/bin:$PATH"
export PATH="$HOME/.local/share/cargo/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
export PATH="$HOME/.pyenv/bin:$PATH"
export PATH="$HOME/.local/share/pyenv/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.surrealdb:$PATH"
export PATH="$HOME/.nix-profile/bin:$PATH"
export PATH="$HOME/.deno/bin:$PATH"
export PATH="$HOME/.local/share/nvim/mason/bin:$PATH"

export PNPM_HOME="/home/gaz/.local/share/pnpm/"
export PATH="$PNPM_HOME:$PATH"

export DENO_HOME="/home/gaz/.deno/bin"
export PATH="$DENO_HOME:$PATH"

export QUARTO_HOME="$HOME/opt/quarto-1.2.335/"
export PATH="$QUARTO_HOME/bin"

# env variables
. /home/gaz/cargo/env

export QT_QPA_PLATFORMTHEME="qt5ct"
export MY_GITHUB="github.com/GazDuckington"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship.toml"

if [ "$(tty)" = "/dev/tty1" ];then
	startx
fi

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"

eval "$(pyenv init -)"
eval "$(starship init bash)"
