#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Lollypop desktop='^5' state=pseudo_tiled
bspc rule -a Stremio desktop='^4'
bspc rule -a Nemo desktop='^3'
bspc rule -a VSCodium desktop='^2'
bspc rule -a Brave-browser desktop='^2'
bspc rule -a kitty desktop='^1'
bspc rule -a pulsemixer state=floating rectangle=800x300+300+20
bspc rule -a Gcolor3 state=floating rectangle=800x300+200+20
# bspc rule -a '*' state=pseudo_tiled

# autostart
~/scripts/idle &
~/scripts/launchb &
nm-applet &
picom -b &
lxpolkit &
touchpad-indicator &
feh --bg-scale --randomize ~/Pictures/Wallpaper/
