#!/usr/bin/env bash
#
# Script name: dmsearch
# Description: Search various search engines (inspired by surfraw).
# Dependencies: dmenu and a web browser
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor
#               Ali Furkan Yıldız

# Defining our web browser.
DMBROWSER="${BROWSER:-firefox}"

# An array of search engines.  You can edit this list to add/remove
# search engines. The format must be: "engine_name]="url".
# The url format must allow for the search keywords at the end of the url.
# For example: https://www.amazon.com/s?k=XXXX searches Amazon for 'XXXX'.
declare -A options
options[archaur]="https://aur.archlinux.org/packages/?O=0&K="
options[archpkg]="https://archlinux.org/packages/?sort=&q="
options[archwiki]="https://wiki.archlinux.org/index.php?search="
options[arxiv]="https://arxiv.org/search/?searchtype=all&source=header&query="
options[bbcnews]="https://www.bbc.co.uk/search?q="
options[duckduckgo]="https://duckduckgo.com/?q="
options[github]="https://github.com/search?q="
options[gitlab]="https://gitlab.com/search?search="
options[lbry]="https://lbry.tv/$/search?q="
options[odysee]="https://odysee.com/$/search?q="
options[reddit]="https://www.reddit.com/search/?q="
options[sourceforge]="https://sourceforge.net/directory/?q="
options[stack]="https://stackoverflow.com/search?q="
options[thesaurus]="https://www.thesaurus.com/misspelling?term="
options[translate]="https://translate.google.com/?sl=auto&tl=en&text="
options[wayback]="https://web.archive.org/web/*/"
options[webster]="https://www.merriam-webster.com/dictionary/"
options[wikipedia]="https://en.wikipedia.org/wiki/"
options[wiktionary]="https://en.wiktionary.org/wiki/"
options[youtube]="https://www.youtube.com/results?search_query="
options[piratebay]="https://pirateproxy.ltda/search.php?q="
# Picking a search engine.
# shellcheck disable=SC2154
while [ -z "$engine" ]; do
    engine=$(printf '%s\n' "${!options[@]}" | sort | dmenu -sb '#16A085'  -i -l 20 -p 'Choose search engine:') "$@" || exit
    url="${options["${engine}"]}" || exit
done

# Searching the chosen engine.
# shellcheck disable=SC2154
while [ -z "$query" ]; do
    query=$(echo "$engine" | dmenu -sb '#16A085'  -p 'Enter search query:') "$@" || exit
done

# Display search results in web browser
$DMBROWSER "$url""$query"

