#!/bin/sh
# /usr/bin/i3exit

# with openrc use loginctl
[ "$(cat /proc/1/comm)" = "systemd" ] && logind=systemctl || logind=loginctl

case "$1" in
    lock)
        betterlockscreen_rapid 5 50
        ;;
    logout)
        bspc quit
        ;;
    switch_user)
        dm-tool switch-to-greeter
        ;;
    suspend)
        betterlockscreen_rapid 5 50 && $logind suspend
        ;;
    hibernate)
        betterlockscreen_rapid 5 50 && $logind hibernate
        ;;
    reboot)
        $logind reboot
        ;;
    shutdown)
        $logind poweroff
        ;;
    *)
        echo "== ! i3exit: missing or invalid argument ! =="
        echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
        exit 2
esac

exit 0
