#!/usr/bin/env bash

rofi_command="rofi -i -matching fuzzy -theme powermenu.rasi"

# Options
shutdown="poweroff "
reboot="reboot "
lock="lock "
suspend="sleep "
logout="logout "

# Variable passed to rofi
options="$shutdown\n$reboot\n$lock\n$suspend\n$logout"

chosen="$(echo -e "$options" | $rofi_command -p 'Quit?' -dmenu -selected-row 2 )"
case $chosen in
    $shutdown)
       systemctl poweroff 
	  ;;
    $reboot)
	    systemctl reboot
    ;;
    $lock)
      ~/scripts/i3lock
    ;;
    $suspend)
    	mpc -q pause
	    playerctl pause
	    amixer set Master mute
      ~/scripts/i3lock
	    systemctl suspend
    ;;
    $logout)
	    killall i3
        killall bspwm
    ;;
esac
