#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width	1
bspc config window_gap		2
bspc config split_ratio		0.52
bspc config top_padding     15

# colors
bspc config focused_border_color "#45A9F9"
bspc config normal_border_color  "#969696"
bspc config active_border_color  "#0FBDBD"

# rules
bspc rule -a VSCodium desktop=^2 follow=off
bspc rule -a kitty desktop=1 follow=off
bspc rule -a pulsemixer state=floating
bspc rule -a nmtui state=floating
bspc rule -a hint state=floating

# autostart
~/scripts/launch-polybar.sh &
xsetroot -cursor_name left_ptr &
~/scripts/mount-gdrive.sh &
~/scripts/idle.sh &
feh --bg-scale --randomize ~/Pictures/Wallpapers/* &
xinput set-prop "ETPS/2 Elantech TrackPoint" "Device Enabled" 0 &
flameshot &
lxpolkit &
picom -b --config "~/.config/picom.conf" &
