#!/bin/sh

rofi_command="rofi -i -matching fuzzy"
chosen="$(ls ~/dktheme/themes | $rofi_command -p '  Themes' -dmenu -no-show-icons
)"
theme_dir=~/dktheme/themes/$chosen
if [ -z "${chosen}" ]; then
  echo cancelled
else
  cp $theme_dir/color.ini ~/.config/polybar/color.ini
  cp $theme_dir/color.sh ~/.config/dk/color.sh
  cp $theme_dir/color.rasi ~/.config/rofi/color.rasi
  nitrogen --set-scaled --save ~/Pictures/Wallpapers/$chosen*
  dkcmd reload
fi
